#!/usr/bin/env python3

import sys, time, argparse, subprocess, os.path

Description = """
Tool to build the EBWT for higly repetive files.
"""

dirname = os.path.dirname(os.path.abspath(__file__))
parse_exe       =  os.path.join(dirname, "circpfp.x")
parseNT_exe     =  os.path.join(dirname, "circpfpNT.x")
bebwtNT_exe      =  os.path.join(dirname, "bebwtNT.x")
bebwtNT64_exe      =  os.path.join(dirname, "bebwtNT64.x")

def main():
    parser = argparse.ArgumentParser(description=Description, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('input', help='input file name', type=str)
    parser.add_argument('-w', '--wsize', help='sliding window size (def. 10)', default=10, type=int)
    parser.add_argument('-p', '--mod', help='hash modulus (def. 100)', default=100, type=int)
    parser.add_argument('-t', help='number of helper threads (def. None)', default=0, type=int)
    parser.add_argument('-r', help='store eBWT in RLE format (def. False)', action='store_true')
    parser.add_argument('-v',  help='verbose',action='store_true')
    parser.add_argument('--parsing',  help='stop after the parsing phase (debug only)',action='store_true')
    args = parser.parse_args()

    logfile_name = args.input + ".log"
    # get main bigbwt directory
    args.bigbwt_dir = os.path.split(sys.argv[0])[0]
    print("Sending logging messages to file:", logfile_name)
    with open(logfile_name,"a") as logfile:

        # ---------- Parsing of the input file
        start0 = start = time.time()

        if args.t>0:
            command = "{exe} {file} -w {wsize} -p {modulus} -t {th}".format(
                    exe = os.path.join(args.bigbwt_dir,parse_exe),
                    wsize=args.wsize, modulus = args.mod, th=args.t, file=args.input)
        else:
            command = "{exe} {file} -w {wsize} -p {modulus}".format(
                    exe = os.path.join(args.bigbwt_dir,parseNT_exe),
                    wsize=args.wsize, modulus = args.mod, file=args.input)

        if args.v: command += " -v"

        print("==== Parsing. Command:", command)
        if(execute_command(command,logfile,logfile_name)!=True):
            return
        print("Elapsed time: {0:.4f}".format(time.time()-start))
        if args.parsing:
            # delete temporary parsing files 
            command = "rm -f {file}.parse_old {file}.last {file}.start {file}.offset {file}.fchar {file}.occ".format(file=args.input)
            if(execute_command(command,logfile,logfile_name)!=True):
                return
            print("==== Stopping after the parsing phase as requested")      
            return

        # ----------- Computing the eBWT of the text
        start = time.time()
        parse_size = os.path.getsize(args.input+".parse")/4
        print("Parse contains " + str(parse_size) + " words.")
        dict_size = os.path.getsize(args.input+".dict")
        print("Dictionary contains " + str(dict_size) + " characters.")
        if(parse_size >=  (2**32-1) or dict_size >=  (2**32-1)):
        #if(True):
            print("running in 64 bit mode")
            command = "{exe} {file} -w {wsize}".format(
                    exe = os.path.join(args.bigbwt_dir,bebwtNT64_exe), wsize=args.wsize, file=args.input)
        else:
            print("running in 32 bit mode")
            command = "{exe} {file} -w {wsize}".format(
                     exe = os.path.join(args.bigbwt_dir,bebwtNT_exe), wsize=args.wsize, file=args.input)

        if(args.r): command += " -r"
        print("==== Computing eBWT of Text. Command:", command)
        if(execute_command(command,logfile,logfile_name)!=True):
            return
        print("Elapsed time: {0:.4f}".format(time.time()-start));
        print("Total construction time: {0:.4f}".format(time.time()-start0))      




# execute command: return True is everything OK, False otherwise
def execute_command(command,logfile,logfile_name,env=None):
  try:
    #subprocess.run(command.split(),stdout=logfile,stderr=logfile,check=True,env=env)
    subprocess.check_call(command.split(),stdout=logfile,stderr=logfile,env=env)
  except subprocess.CalledProcessError:
    print("Error executing command line:")
    print("\t"+ command)
    print("Check log file: " + logfile_name)
    return False
  return True
  

if __name__ == '__main__':
    main()
